<?php

namespace App\Services\Hostsharing;

use Illuminate\Support\Collection;

class User
{
    public static function create(array $attributes)
    {
        $attributes['comment'] ??= 'Generated by StuFis-Manager';
        self::query()->set($attributes)->execute('add');
    }

    private static function query(): HostsharingScripts
    {
        return new HostsharingScripts('user');
    }

    public static function search($filter): Collection
    {
        return self::query()->where($filter)->execute('search');
    }
}
